alerting:
  telegram:
    token: ""
    id: ""
    default-alert:
      enabled: true
      send-on-resolved: true
      failure-threshold: 1
      success-threshold: 1
 
endpoints:
  - name: web
    group: internet
    url: "https://www.../"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
#      - "[BODY].status == UP"
      - "[RESPONSE_TIME] < 2000"
      - "[CERTIFICATE_EXPIRATION] > 72h"
    alerts:
      - type: telegram
 
  - name: eybox
    group: internet
    url: "https://box.../"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"  
    alerts:
      - type: telegram
 
  - name: OWA
    group: internet
    url: "https://mail.../"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: telegram
  - name: example-dns-query
    url: "8.8.8.8" # Address of the DNS server to use
    interval: 5m
    dns:
      query-name: "www..."
      query-type: "A"
    conditions:
      - "[BODY] == ..."
      - "[DNS_RCODE] == NOERROR"
     alerts:
      - type: telegram
  - name: icmp-ping
    url: "icmp://8.8.8.8"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
     alerts:
      - type: telegram
  - name: mail
    url: "tcp://mail...:25"
    interval: 1m
    conditions:
      - "[CONNECTED] == true" 
     alerts:
      - type: telegram       
storage:
  type: sqlite
  path: /data/data.db
